/opt/cray/pe/modules/3.2.11.4/bin/modulecmd: error while loading shared libraries: libtcl8.6.so: cannot open shared object file: No such file or directory
/opt/cray/pe/modules/3.2.11.4/bin/modulecmd: error while loading shared libraries: libtcl8.6.so: cannot open shared object file: No such file or directory
/opt/cray/pe/modules/3.2.11.4/bin/modulecmd: error while loading shared libraries: libtcl8.6.so: cannot open shared object file: No such file or directory
/opt/cray/pe/modules/3.2.11.4/bin/modulecmd: error while loading shared libraries: libtcl8.6.so: cannot open shared object file: No such file or directory
ls: cannot access 'mechs/*.inc': No such file or directory
/global/homes/m/mikelam/.bashrc: line 10: module: command not found
/global/homes/m/mikelam/.bashrc: line 11: module: command not found
/global/homes/m/mikelam/.bashrc: line 12: module: command not found
/global/homes/m/mikelam/.bashrc: line 13: module: command not found
/global/homes/m/mikelam/.bashrc: line 10: module: command not found
/global/homes/m/mikelam/.bashrc: line 11: module: command not found
/global/homes/m/mikelam/.bashrc: line 12: module: command not found
/global/homes/m/mikelam/.bashrc: line 13: module: command not found
/global/homes/m/mikelam/.bashrc: line 10: module: command not found
/global/homes/m/mikelam/.bashrc: line 11: module: command not found
/global/homes/m/mikelam/.bashrc: line 12: module: command not found
/global/homes/m/mikelam/.bashrc: line 13: module: command not found
/global/homes/m/mikelam/.bashrc: line 10: module: command not found
/global/homes/m/mikelam/.bashrc: line 11: module: command not found
/global/homes/m/mikelam/.bashrc: line 12: module: command not found
/global/homes/m/mikelam/.bashrc: line 13: module: command not found
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/bpop/
Traceback (most recent call last):
  File "/global/u1/m/mikelam/SimulatingVariants/Optimization_HHtoHMM.py", line 9, in <module>
    import bluepyopt as bpop
ModuleNotFoundError: No module named 'bluepyopt'
srun: error: nid00809: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=53135439.0
